### ISSUE TITLE
[IMPL] Anzeige und Editierbarkeit aller Blacklistwörter

### ISSUE THREAD

**Issue by kluckow** [kluckow/netspy#17]
Hier wird ein DefaultListModel verlangt.
Hier kann vermutlich die getBlacklist()-Methode im EmailHandler verwendet werden, um an die liste heranzukommen.
Zum Hinzufügen, also Schreiben in die Datei gibt es schon eine Methode im TextWriter, erreichbar über FileManager.
Bräuchten also noch eine Methode zum Editieren, also Schreiben mit bisschen Extra-Code.
Und hierfür werden wir wohl auch das Layout des NetSpyFrames anpassen müssen, da das alles hier Platz in Anspruch nimmt. :sob: 
Also:
- [x] Anzeige der Blacklistwörter in einer Liste (selektierbar, single_selection_mode)
- [x] Editier-Möglichkeit eines Wortes
- [x] Lösch-Möglichkeit eines Wortes und aller Wörter
- [x] Hinzufügen-Möglichkeit eines Worters

**Comment by niinhu** [comment]
Bin ich da jetzt auf dem Holzweg?! 
Wir wollten die Editierbarkeit der Blackword-Liste weglassen oder ?
Falls ja dann close einfach....
