### ISSUE TITLE
Singleton Pattern aus Klassen entfernen

### ISSUE THREAD

**Issue by kluckow** [kluckow/netspy#2]
Die singletons sind eigentlich überflüssig und sollten daher durch herkömmliche klassen ersetzt werden.

**Comment by niinhu** [comment]
Folgende Klassen enthalten singelton:
- EmailHandler (DONE)
- FileManager (DONE) 
- LogManager (DONE)
- alle Util-Klassen (DONE)

**Comment by niinhu** [comment]
Um vom singelton in normale Klassen zu ändern müssen folgende Schritte durchgeführt werden:
- getInstance() muss entfernt werden
- constructor von private auf public setzten oder evtl entfernen
- Instanzvariable der muss entfernt werden z.B: private static EmailHandler emailHandler = null;
- Die Änderungen an an den anderen Stellen im Code anpassen

**Comment by kluckow** [comment]
Habe es mal testweise am EmailHandler ausprobiert.
Das Objekt, das vorher mit .getInstance() aufgerufen wurde, wird nun mit static (nur im NetSpy static) initialisiert. Für andere Objekte sollte es genügen eine private Instanzvariable zu verwenden.

**Comment by kluckow** [comment]
Btw, lass dich nicht von diesem "undo changes" commit ablenken, hab da nur was gestetet
