### ISSUE TITLE
[QS] Überprüfung der Korrektheit aller Access Modifier

### ISSUE THREAD

**Issue by kluckow** [kluckow/netspy#23]
Hier müssen alle `public`-modifiers an `public static final` Instanzvariablen und Methoden überprüft werden.
Man kann in Eclipse Variablen mit dem Cursor fokussieren und dann `Strg+Alt+H` drücken, um sich die **Call Hierarchy** anzeigen zu lassen.
Wird eine Methode/Variable auch außerhalb verwendet, kann der Access Modifier ruhig public bleiben.
Wird eine Methode nicht außerhalb verwendet, soll sie auf private gesetzt werden. Wird diese `private`-Variable/Methode in dieser Klasse dann auch nicht verwendet, so kann sie komplett gelöscht werden.
**Tip**: Manchmal geht es schneller bei vermuteten überflüssigen `public`-Modifiers einfach mal auf `private` setzen und schauen, in welchen Klassen Eclipse dann die Errors anzeigt. Wenn Errors angezeigt werden, bleibt es halt `public`.

**Comment by niinhu** [comment]
so bin nochmal alles durchgegangen sollte aber jetzt passen...

**Comment by kluckow** [comment]
habe grad auch nochmal ordentlich refactored, etc.

**Comment by kluckow** [comment]
Aber in dem NetSpyFrame gibt es noch einiges zu refactorn, speziell das NetSpyFrame:
1. GUI-Komponenten, die als Instanzvariable gesetzt werden, sollten mit `btnDiesDas` und nicht `getBtnDiesDas()` aufgerufen werden
