### ISSUE TITLE
[QS] Manuelle Tests

### ISSUE THREAD

**Issue by kluckow** [kluckow/netspy#24]
Bevor das Projekt abgegeben wird, sollten wir alle Anwendungsfälle nochmal manuell testen, sobald wir es als fertig empfinden. Hätte ja gerne Unit-Tests gemacht, einfach so als Übung, aber dafür bleibt leider keine Zeit mehr, so wie es aussieht :cry:

**Comment by niinhu** [comment]
hab soweit mal durchgetestet... außer dem problem mit der falschen/leeren config ist mir kein fehler aufgetreten... aber dann geben wir das ding im besten fall ohne ab und dann wird sie ja beim ersten start automatisch erstellt...

**Comment by kluckow** [comment]
ja, den fall müssen wir dann auch mal machen, alle nötigen dateien zusammenlegen, zippen, und dann versuchen zu kompilieren via console und dann gucken was passiert. das wird so der finale test.

**Comment by kluckow** [comment]
aber kannst ruhig mal nen ticket anlegen für diese null pointer exception, wenn die config.properties leer ist
