### ISSUE TITLE
[IMPL] Logging implementieren

### ISSUE THREAD

**Issue by kluckow** [kluckow/netspy#3]
Hier nochmal schauen wie das Format der Logs aussehen soll und dann entsprechend im Code anpassen.
- [x] Format der Logs definieren
- [x] Paar mal testen

**Comment by niinhu** [comment]
Das Logging wird erst nach bearbeitung der Singelton Pattern implementiert!

**Comment by kluckow** [comment]
Das Logging findet statt, kurz vor dem Verschieben der Mails. Unser Logger nimmt ein ScanResult-Objekt beim Loggen entgegen. Dieses ScanResult wiederum wird mit einem Email-Objekt und einer hitMap initialisiert.

**Comment by kluckow** [comment]
Der Logger nimmt ein Email-Objekt entgegen und zieht sich da die jeweiligen Properties raus und formatiert schön. dann soll er eine log.txt erstellen und alle log einträge in dieselbe datei schreiben (append).
Ist eigentlich so weit implementiert, muss nur noch optimiert werden.
