### ISSUE TITLE
[IMPL] Implementierung des MyActionListener für alle Buttons im MyJFrame

### ISSUE THREAD

**Issue by kluckow** [kluckow/netspy#6]
Schritt 1) wäre die Button-Namen public static im MyJFrame zu setzen und entsprechend zu verwenden.
Im Schritt 2) muss dann der MyActionListener erstellt werden. Dazu die überschriebene Methode actionPerformed. In dieser wird dann in einer switch-case auf Button Clicks, je nach Button Name, reagiert.
Aktuell folgende TODOs:
- [x] Start Scan Button fehlt noch im FileChooserActionListener
- [x] Implementierung der Funktionalitäten der 5 Button im FileChooserActionListener:

:arrow_right: 
- [x] Mail Path (inkl. File/Dir Validation)
- [x] Blackword Path (inkl. File Validation)
- [x] Log Path (inkl. Dir Validation)
- [x] Quarantine Path (inkl. Dir Validation)
- [x] Validierung auf "blacklist.txt"-Dateien beim Auswählen der Blackword-Datei (Datei muss "blacklist.txt heißen)
- [x] Validierung auf special characters bei den directories für Quarantäne- und Log-Verzeichnis (mal schauen, ob das überhaupt notwendig ist)
- [x] Start Scan (hier muss nur geprüft werden, ob alle Input-Felder für die Pfade != null oder != "" sind)
- [x] Alle Pfade werden beim Auswählen über den JFileChooser in der config.properties gesetzt
- [x] In den TextFields eingegebene Pfade, die noch nicht existieren, müssen erstellt werden
- [x] Log-Verzeichnis UND LogDatei-Name müssen editierbar sein (und Anpassungen im Listener/FileManager werden nötig sein, denke ich)

**Comment by kluckow** [comment]
Hier eine TODO-Liste die abgehakt werden kann:
- [x] Button-Names im MyJFrame public static final machen, weil wir diese später in dem ActionListener benötigen (Bsp: public static final BUTTON_ID_MAIL_PATH = "button_mail_path";)
- [x] MyActionListener implementieren (implements ActionListener)
- [x] in MyActionListener in der @Override actionPerformed-Methode eine switch-case erstellen, die jeweils den button-Namen (Zugriff über die public static final button ids) des geclickten buttons checked und je nach button name erstmal ein `//TODO: implement filechooser here`

**Comment by kluckow** [comment]
Habe das auch schon ansatzweise für den Mail-Path-Chooser implementiert.
man kann dort momentan eine Datei  oder ein Verzeichnis auswählen. Dieses wird dann nach Bestätigung in das entsprechende Textfeld gesetzt.

Btw: habe auch überlegt die TextFields **ausschileßlich** über den JFileChooser editierbar zu machen.

**Comment by kluckow** [comment]
- [ ] Start Scan Button fehlt noch im FileChooserActionListener
- [ ] Implementierung der Funktionalitäten der 5 Button im FileChooserActionListener

**Comment by niinhu** [comment]
Ich hab mal den Rest gemacht :smile:... also momentan funktionieren die Buttons mit übernahme der Pfade und der jeweiligen Fehlermeldung.
willst du noch die Fehlermeldungen mit ins Log übernehmen ? wäre glaube ich schwachsinnig aber naja

**Comment by kluckow** [comment]
Jo, sieht gut aus soweit!
Ja, die Fehlermeldungen brauchen wir nicht mehr loggen, find ich.
